version: "3"
services:
  boberto-web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    container_name: boberto-web
    volumes:
      - ./web:/var/www/html
      - ./web/config/php.ini:/usr/local/etc/php/php.ini
  redis-compose:
    image: redis
    restart: always
    container_name: boberto-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    env_file:
      - .env
    hostname: redis
    ports:
      - "6379:6379"