name: Deploy de produção

on:
  push:
    branches:    
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/brutalzinn/launcher"

    - name: Adicionado chave do Discord
      uses: appleboy/ssh-action@master
      env:
        BOBERTO_DATABASE: ${{ secrets.BOBERTO_DATABASE }}
        BOBERTO_HOST: ${{ secrets.BOBERTO_HOST }}
        BOBERTO_USER: ${{ secrets.BOBERTO_USER }}
        BOBERTO_PASSWORD: ${{ secrets.BOBERTO_PASSWORD }}
        BOBERTO_PORT: ${{ secrets.BOBERTO_PORT }}
        API_PORT: ${{ secrets.API_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DISCORD_KEY: ${{ secrets.DISCORD }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
        API_HEADER: ${{ secrets.API_HEADER }}

      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: BOBERTO_DATABASE, BOBERTO_USER, BOBERTO_PASSWORD, BOBERTO_PORT, BOBERTO_HOST, JWT_SECRET, API_PORT, DISCORD_URL, DISCORD, REDIS_PASSWORD, REDIS_PORT, API_HEADER
        script: |
          sudo rm -f .env
          echo "BOBERTO_HOST=$BOBERTO_HOST" >>/home/brutalzinn/launcher/.env
          echo "JWT_SECRET=$JWT_SECRET" >>/home/brutalzinn/launcher/.env
          echo "BOBERTO_DATABASE=$BOBERTO_DATABASE" >>/home/brutalzinn/launcher/.env
          echo "BOBERTO_USER=$BOBERTO_USER" >>/home/brutalzinn/launcher/.env
          echo "BOBERTO_PASSWORD=$BOBERTO_PASSWORD" >>/home/brutalzinn/launcher/.env
          echo "BOBERTO_PORT=$BOBERTO_PORT" >>/home/brutalzinn/launcher/.env
          echo "API_PORT=$API_PORT" >>/home/brutalzinn/launcher/.env
          echo "DISCORD_KEY=$DISCORD_KEY" >>/home/brutalzinn/launcher/.env
          echo "DISCORD_URL=$DISCORD_URL" >>/home/brutalzinn/launcher/.env
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >>/home/brutalzinn/launcher/.env
          echo "REDIS_PORT=$REDIS_PORT" >>/home/brutalzinn/launcher/.env
          echo "API_HEADER=$API_HEADER" >>/home/brutalzinn/launcher/.env         
          echo "ENVIROMENT=PRODUCTION" >>/home/brutalzinn/launcher/.env

    - name: Disparando notificação no Discord pré deploy
      uses: appleboy/ssh-action@master
      env:
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DISCORD_URL
        script: |
          DATA=$(date '+%d-%m-%Y %H:%M:%S') &&
          CONTENT="Preparando para atualizar web api... - $DATA" &&
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"'"$CONTENT"'"}' $DISCORD_URL

    - name: Executando docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script_stop: true
        script: |
          cd /home/brutalzinn/launcher
          docker-compose down >> compose.log 2>&1 &
          docker rm -f $(docker ps -a -q) >> compose.log 2>&1 &
          docker volume rm $(docker volume ls -q) >> compose.log 2>&1 &
          docker-compose up -d >> compose.log 2>&1 &

    - name: Disparando notificação no Discord
      uses: appleboy/ssh-action@master
      env:
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DISCORD_URL
        script: |
          DATA=$(date '+%d-%m-%Y %H:%M:%S') &&
          CONTENT="O deploy da web api foi um sucesso. $DATA" &&
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"'"$CONTENT"'"}' $DISCORD_URL